"""Jinja2-based documentation renderer.

Renders a DocumentationDraft into Markdown or plain text
using Jinja2 templates from the templates/ directory.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from intellapi.llm.schemas import DocumentationDraft

# Template directory (relative to this file)
_TEMPLATE_DIR = Path(__file__).parent.parent / "templates"


def render_markdown(draft: DocumentationDraft) -> str:
    """Render a DocumentationDraft as Markdown."""
    env = _create_env()
    try:
        template = env.get_template("documentation.md.j2")
        return template.render(doc=draft)
    except Exception:
        # Fallback: render directly without template
        return _fallback_markdown(draft)


def render_plaintext(draft: DocumentationDraft) -> str:
    """Render a DocumentationDraft as plain text."""
    env = _create_env()
    try:
        template = env.get_template("documentation.txt.j2")
        return template.render(doc=draft)
    except Exception:
        # Fallback: strip markdown from the MD render
        md = render_markdown(draft)
        return _strip_markdown(md)


def _create_env() -> Environment:
    """Create a Jinja2 environment with the templates directory."""
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        autoescape=select_autoescape([]),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def _fallback_markdown(draft: DocumentationDraft) -> str:
    """Generate markdown directly when templates are unavailable."""
    lines: list[str] = []

    lines.append(f"# API Documentation\n")
    lines.append(f"## Overview\n\n{draft.service_overview}\n")

    if draft.auth_summary:
        lines.append(f"## Authentication\n\n{draft.auth_summary}\n")

    if draft.endpoints:
        lines.append("## Endpoints\n")
        for ep in draft.endpoints:
            lines.append(f"### `{ep.method}` {ep.path}\n")
            lines.append(f"{ep.summary}\n")
            if ep.description:
                lines.append(f"{ep.description}\n")

            if ep.parameters:
                lines.append("**Parameters:**\n")
                lines.append("| Name | Location | Type | Required | Description |")
                lines.append("|------|----------|------|----------|-------------|")
                for p in ep.parameters:
                    req = "Yes" if p.required else "No"
                    lines.append(f"| {p.name} | {p.location} | {p.type} | {req} | {p.description} |")
                lines.append("")

            if ep.example_request:
                lines.append(f"**Example Request:**\n```\n{ep.example_request}\n```\n")

            if ep.example_response:
                lines.append(f"**Example Response:**\n```\n{ep.example_response}\n```\n")

    if draft.models:
        lines.append("## Data Models\n")
        for model in draft.models:
            lines.append(f"### {model.name}\n")
            if model.description:
                lines.append(f"{model.description}\n")
            if model.fields:
                lines.append("| Field | Type | Required | Description |")
                lines.append("|-------|------|----------|-------------|")
                for f in model.fields:
                    req = "Yes" if f.required else "No"
                    lines.append(f"| {f.name} | {f.type} | {req} | {f.description} |")
                lines.append("")

    if draft.error_handling:
        lines.append(f"## Error Handling\n\n{draft.error_handling}\n")

    if draft.dependencies:
        lines.append(f"## Dependencies\n\n{draft.dependencies}\n")

    if draft.example_usage:
        lines.append("## Usage Examples\n")
        for ex in draft.example_usage:
            lines.append(f"### {ex.title}\n")
            lines.append(f"{ex.description}\n")
            lines.append(f"```{ex.language}\n{ex.code}\n```\n")

    if draft.caveats:
        lines.append("## ⚠️ Uncertain / Needs Verification\n")
        for caveat in draft.caveats:
            lines.append(f"- {caveat}")
        lines.append("")

    lines.append(
        "\n---\n*Generated by [Intellapi](https://github.com/intellapi/intellapi)*\n"
    )

    return "\n".join(lines)


def _strip_markdown(md: str) -> str:
    """Crude markdown-to-plaintext conversion."""
    import re
    text = md
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    text = re.sub(r"\|[-\s|]+\|", "", text)
    return text
